name: Python Lint with Pylint

# Trigger the workflow on push or pull request events for the main branch
on:
  push:
    branches: ["main", "master"] 
  pull_request:
    branches: ["main", "master"] 

jobs:
  lint:
    name: Run Pylint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4 
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Pylint
      run: |
        pylint your_project_directory/ > pylint_report.txt || true

    - name: Upload Pylint Report
      uses: actions/upload-artifact@v3.1.2
      with:
        name: pylint-report
        path: pylint_report.txt